FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY indexConsumers.js ./
RUN mkdir -p salesforce-service/consumers
COPY tests/integration/UserConsumer.test.js ./tests/integration/
COPY salesforce-service/UserCRUD.js salesforce-service/salesforce.js salesforce-service/heartbeat.js salesforce-service/rabbitmq.js ./salesforce-service 
COPY salesforce-service/consumers ./salesforce-service/consumers
CMD ["npm", "run", "consume"]
