networks:
  attendify_net_testing:
    external: true

services:
  crm_salesforce_testing_consumers:
    build:
      context: .
      dockerfile: Dockerfile.consumers
    networks:
      - attendify_net_testing
    env_file:
      - .env
    container_name: crm_salesforce_testing_consumers
    restart: always

    
  crm_salesforce_testing_producers:
    build:
      context: .
      dockerfile: Dockerfile.producers
    networks:
      - attendify_net_testing
    env_file:
      - .env
    container_name: crm_salesforce_testing_producers
    restart: always
