networks:
  attendify_net:
    external: true

services:
  crm_consumers:
    build:
      context: .
      dockerfile: Dockerfile.consumers
    networks:
      - attendify_net
    env_file:
      - .env
    container_name: crm_salesforce_testing_consumers

    
  crm_producers:
    build:
      context: .
      dockerfile: Dockerfile.producers
    networks:
      - attendify_net
    env_file:
      - .env
    container_name: crm_salesforce_testing_producers
