FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY indexProducers.js .env ./
RUN mkdir -p salesforce-service/producers
COPY ./salesforce-service/salesforce.js ./salesforce-service/heartbeat.js ./salesforce-service
COPY ./salesforce-service/producers ./salesforce-service/producers
CMD ["npm", "run", "produce"]
