# change "brent" to the name of your branch

name: Work CI/CD Pipeline

on:
  push:
    branches: [ "brent" ]

permissions:
  contents: write
  actions: write

jobs:
  dev-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

