# change "brent" to the name of your branch

name: Work CI/CD Pipeline

on:
  push:
    branches: [ "brent" ]

permissions:
  contents: write
  actions: write

jobs:
  dev-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Push to dev branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin
          git checkout dev
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git merge origin/brent --strategy=recursive --allow-unrelated-histories -X theirs -m "Merge brent into dev"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} dev
